### ISSUE TITLE
ValueError in notebooks/proteomics_data_relaxations.ipynb cell 17 line 1. 

### ISSUE THREAD

**Issue by Soratake-HirotakaYajima** [ginkgobioworks/geckopy#12]
Hello.

I got a ValueError in notebooks/proteomics_data_relaxations.ipynb cell 17 line 1.

Perhaps, it is lack of data about MW.

Could you tell me about error below.

Best regards.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/userName/geckopy/simult_supp_material/notebooks/proteomics_data_relaxations.ipynb セル 17 line 1
----> 1 ev9_valid["MW"] = extract_proteins(None, prot_dict)["MW"]

File ~/.pyenv/versions/3.8.18/envs/geckopy/lib/python3.8/site-packages/geckopy/experimental/molecular_weights.py:194, in extract_proteins(model, all_proteins, key_fn)
    192 df_prot["MW"] = 0
    193 for index, row in df_prot.iterrows():
--> 194     df_prot.loc[index, "MW"] = _molecular_weight(row["Sequence"])
    195 return df_prot[["uniprot", "protein_id", "MW", "Sequence"]]

File ~/.pyenv/versions/3.8.18/envs/geckopy/lib/python3.8/site-packages/geckopy/experimental/molecular_weights.py:95, in _molecular_weight(seq)
     93     weight = sum(weight_table[x] for x in seq) - (len(seq) - 1) * water
     94 except KeyError as e:
---> 95     raise ValueError(
     96         f"'{e}' is not a valid unambiguous letter for proteins"
     97     ) from None
     99 return weight

ValueError: ''X'' is not a valid unambiguous letter for proteins

**Comment by carrascomj** [comment]
I have just left a comment about this at https://github.com/carrascomj/simult_supp_material/issues/1#issuecomment-1776788023, let's handle it there.
