### ISSUE TITLE
AttributeError: module 'geckopy' has no attribute 'io'

### ISSUE THREAD

**Issue by kavousisiavash** [ginkgobioworks/geckopy#14]
Hi 
Recently, according to the instructions, of course, I install geckopy. First through Anaconda and then once with cmd , but now I get this error.

after this 

AttributeError: module 'geckopy' has no attribute 'io'

from os.path import join, pardir

import geckopy

ROOT = pardir
DATA = join(ROOT, "tests", "data")
ec_model = geckopy.io.read_sbml_ec_model(join(DATA, "eciML1515.xml.gz"))

**Comment by carrascomj** [comment]
geckopy 3.0 (this one) is not yet in pypi. It must be installed from source (otherwise you would be installing [this one](https://github.com/SysBioChalmers/GECKO/tree/gecko2/geckopy)):

```bash
pip install git+https://github.com/ginkgobioworks/geckopy.git
```

Sorry about the confusion. If this is not the problem, let me know and I can give it a check.

**Comment by kavousisiavash** [comment]
Thank you for your response. But when I run the code you sent, I get the
error in the email attachment. Should I delete the previous one and then
run your code?

**Comment by carrascomj** [comment]
Not super sure about the "email attachment" part (I _don't_ think github allows for that) but I'd recommend for installing geckopy in a fresh environment, yes.

**Comment by kavousisiavash** [comment]
By the way, it is interesting that when I run another example that has
"io." It doesn't object to it and it objects to not installing another
package "pytfba"

**Comment by carrascomj** [comment]
Yes, if you need to run TFA, you need to install "pytfa" (not installed by default).

**Comment by kavousisiavash** [comment]
i'm install in your way 
but still

import geckopy
ROOT = pardir
DATA = join(ROOT, "tests", "data")
ec_model = geckopy.io.read_sbml_ec_model(join(DATA, "eciML1515.xml.gz"))
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2024.1\plugins\python-ce\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
  File "<input>", line 1, in <module>
AttributeError: module 'geckopy' has no attribute 'io'

**Comment by kavousisiavash** [comment]
![inpycharm](https://github.com/ginkgobioworks/geckopy/assets/137698332/95c72aae-ec57-49d9-bf00-a6398c20fb3e)
in pycharm

**Comment by carrascomj** [comment]
It seems like you are not installing it in the environment/python that pycharm is using (you should not get geckopy 2.0.2). I am not familiar with pycharm, so I cannot help you there. Again, this geckopy is not in PyPI, so any 2.0.2 geckopy installed from PyPI is the wrong geckopy.

**Comment by kavousisiavash** [comment]
thank you very much
Your help was useful

**Comment by carrascomj** [comment]
Closing this, feel free to reopen if the same issue arises.

**Comment by kavousisiavash** [comment]
HI AGAIN

Unfortunately, I have not succeeded in installing the correct version yet. May I get more complete guidance?
In the visual studio installer, click on launch and in the Developer command prompt for VS 2022 environment, these commands were executed in the following order.

First, I created an environment called geckopy
py -m venv geckopy
Then I activated the environment with this command
.\geckopy\Scripts\activate
(The above two commands were done according to the strict suggestion (highly recommended) of the link below, which of course is old)
https://geckopy.readthedocs.io/en/latest/installation.html
Then on the way
C:\users\siavash\geckopy\docs
(geckopy) C:\Users\Siavash\geckopy\docs>pip install -r requirements.txt
pip install -r requirements.txt
It was implemented that result
Successfully installed Jinja2-3.1.4 PyYAML-6.0.1 alabaster-0.7.16 astroid-3.2.3 attrs-23.2.0 babel-2.15.0 backcall-0.2.0 beautifulsoup4-4.12.3 bleach-6.1.0 certifi-2024.7 .4 charset-normalizer-3.3.2 colorama-0.4.6 decorator-5.1.1 defusedxml-0.7.1 docutils-0.21.2 fastjsonschema-2.20.0 idna-3.7 imagesize-1.4.1 ipython-7.24.0 jedi-0.19 .1 jsonschema-4.23.0 jsonschema-specifications-2023.12.1 jupyter-client-8.6.2 jupyter-core-5.7.2 jupyterlab-pygments-0.3.0 markupsafe-2.1.5 matplotlib-inline-0.1.7 mistune-3.0 .2 nbclient-0.10.0 nbconvert-7.16.4 nbformat-5.10.4 nbsphinx-0.9.4 packaging-24.1 pandocfilters-1.5.1 parso-0.8.4 pickleshare-0.7.5 platformdirs-4.2.2 pockets-0.9.1 prompt-toolkit-3.0.47 pygments-2.18.0 python-dateutil-2.9.0.post0 pywin32-306 pyzmq-26.0.3 referencing-0.35.1 requests-2.32.3 rpds-py-0.19.0 six-1.16. 0 snowballstemmer-2.2.0 soupsieve-2.5 sphinx-3.5.3 sphinx-autoapi-1.7.0 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib -napoleon-0.7 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.4 tinycss2-1.3.0 tornado-6.4.1 traitlets-5.14.3 unidecode-1.3.8 urllib3-2.2.2 wcwidth-0.2.13 webencodings- 0.5.1
Then in the geckopy main folder (downloaded from github)
https://github.com/ginkgobioworks/geckopy.git

(geckopy) C:\Users\Siavash\geckopy>pip install.
This command was executed.
INFO: pip is looking at multiple versions of geckopy to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement cobra~=0.27.0 (from geckopy) (from versions: none)
ERROR: No matching distribution found for cobra~=0.27.0

**what is wrong?**

**Comment by carrascomj** [comment]
First, you are installing the requirements for building the documentation, you should not.

Second, the `pip install .` once in the geckopy folder looks alrite to me. About how it does not match that cobra version, I am a bit unsure, I will try to repro this myself.

**Comment by kavousisiavash** [comment]
Thank you
Someone made some suggestions and I did them. (Although I had uninstalled the wrong package (geckopy 2.0.2), but I checked and it was still in cmd and I removed it then this time I got this error. Apparently, the previous error was fixed

pandas\_libs/algos.c(787): fatal error C1083: Cannot open include file: 'numpy/arrayobject.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.40.33807\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for pandas
Successfully built geckopy
Failed to build pandas
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pandas)

**Comment by kavousisiavash** [comment]
![image](https://github.com/user-attachments/assets/3e951a70-b0f4-43a4-9cff-b2dcabd109d1)

**Comment by kavousisiavash** [comment]
> ```shell
> ```shell
> pip install git+https://github.com/ginkgobioworks/geckopy.git
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

I tried this recipe several times. But I got this error
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/b2/fe/81695a1aa331a842b582453b605175f419fe8540355886031328089d840a/sympy-1.13.1-py3-none-any.whl.metadata (Caused by ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)))

![image](https://github.com/user-attachments/assets/71568405-8f2c-40c8-804b-635cae0c6223)

**Comment by carrascomj** [comment]
That looks like a bug with sympy. The version is picking was released 4 hours ago, there might be some error with the distribution. Check if first installing a previous version works:

```sh
pip install "sympy==1.12.1"
pip install git+https://github.com/ginkgobioworks/geckopy.git
```

**Comment by kavousisiavash** [comment]
Hello
Thanks for your guidance. I followed your instructions and it didn't work. Although one of the colleagues was able to use this link
https://github.com/ginkgobioworks/geckopy
to install, surprisingly, the version installed by her is version = 0.0.1. Following this contradiction, when we searched the files in the link above, the version = 0.0.1 was written in the setup.cfg file. This file was uploaded ten months ago.
[metadata]
name = geckopy
description = Enzyme Constraint genome-scale models
keywords =
 python
 metabolic-models
 bioinformatics
 systems-biology
long_description = file: README.md
version = 0.0.1

Now the question is whether this version is the latest version and the name is just written wrong or is there another problem?

**Comment by carrascomj** [comment]
Yes, the version number was changed since it was not published to pypi. `0.0.1` is _correct_.

**Comment by kavousisiavash** [comment]
hello
After disturbing you several times and the help of one of my colleagues, I think I took the first step correctly. Thank you very much.
This is how I installed the package. First I created an environment : 
py -m venv geckopy 
.\geckopy\scripts\activate 

then 
git clone https://github.com/ginkgobioworks/geckopy.git
cd geckopy 
pip install . 

Although these errors were taken but

note: This error originates from a subprocess, and is likely not a problem with pip.
 ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects

but 
Successfully built geckopy

![image](https://github.com/user-attachments/assets/a182201b-8654-4bb2-8b9f-b9e383bb6007)


of course when i run this code 

import pandas as pd
from geckopy.experiment import from_copy_number

raw_proteomics = pd.read_csv("tests/data/ecoli_proteomics_schmidt2016S5.tsv")
exp_model = from_copy_number(
    model,
    index=raw_proteomics["uniprot"],
    cell_copies=raw_proteomics["copies_per_cell"],
    stdev=raw_proteomics["stdev"],
    vol=2.3,
    dens=1.105e-12,
    water=0.3,
)
exp_model.optimize()

i got this error : 

ModuleNotFoundError: No module named 'geckopy.experiment'

**Comment by kavousisiavash** [comment]
As a last comment, the last problem was solved like this

print(dir(geckopy))

['Model', 'Protein', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'experimental', 'flux_analysis', 'flux_variability_analysis', 'io', 'model', 'protein', 'reaction']

I ran this code and realized that probably module "experiment" has been renamed to "experimental". 
Then I ran this code and no error was given.

import pandas as pd
from geckopy.experimental import from_copy_number

raw_proteomics = pd.read_csv("tests/data/ecoli_proteomics_schmidt2016S5.tsv")
exp_model = from_copy_number(
    model,
    index=raw_proteomics["uniprot"],
    cell_copies=raw_proteomics["copies_per_cell"],
    stdev=raw_proteomics["stdev"],
    vol=2.3,
    dens=1.105e-12,
    water=0.3,
)
exp_model.optimize()

Just the answer said that some proteins were not found in the model from the measurements.

Sorry if I commented too much here. I hope it solves the problem for newcomers like me.

**Thank you very much**
